//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietChamLearn_BuiVanChat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id_cate { get; set; }
        public string Name_cate { get; set; }
        public string Slug_cate { get; set; }
        public bool Hide { get; set; }
    }
}
