//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietChamLearn_BuiVanChat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id_Menu { get; set; }
        public string Name_Menu { get; set; }
        public string Slug { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
