//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietChamLearn_BuiVanChat_18607075.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Id_Word { get; set; }
        public string Viet_Word { get; set; }
        public string Cham_Word { get; set; }
        public string Description_Word { get; set; }
        public string Image_Word { get; set; }
        public string Void_Word { get; set; }
        public Nullable<bool> Hide_Word { get; set; }
        public string Characters_Word { get; set; }
    }
}
